### PR TITLE
updated PA.py

### PR DESCRIPTION
**Pull request by saiadityaviswanadham**
To capture the image using webcam using Python Assistant, ecapture module of python is implemented

### CODE REVIEW

**Comment by anandxkumar** [comment]
Hello @saiadityaviswanadham, it will be great if you remove the `__pycache__` . Even better add a `.gitignore` file and add the directory `__pyache__` to it so that the temporary files will not be added in the commit, to keep the code clean!

**Comment by saiadityaviswanadham** [comment]
@anandxkumar I have added the .gitignore file and added the __pyache__ directory to it. Thanks

**Comment by anandxkumar** [comment]
Seems like the `__pycache__` has already been committed. Therefore you will need to manually delete it or use `git rm -r __pycache__` to remove the folder and again commit it so that it all the temporary `pyc` files won't be added again.

For reference:  https://stackoverflow.com/questions/65738611/why-does-git-ignore-not-work-for-pycache-folder

**Comment by saiadityaviswanadham** [comment]
I have deleted the __pycache__ folder. Can you check and let me know once..

**Comment by anandxkumar** [comment]
Nice :+1:

**Comment by anandxkumar** [comment]
Fixes #14

**Pull request merged**
